// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kampong_goods;

#nullable disable

namespace kampong_goods.Migrations.VoucherDb
{
    [DbContext(typeof(VoucherDbContext))]
    [Migration("20230116081117_voucher")]
    partial class voucher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("kampong_goods.Models.Voucher", b =>
                {
                    b.Property<string>("VoucherId")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("VoucherDiscAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VoucherExpDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VoucherMinSpend")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoucherName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("VoucherId");

                    b.ToTable("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
